name = "controle-ponto"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./"

# Banco de dados D1
[[d1_databases]]
binding = "DB"
database_name = "controle-ponto-db"
database_id = "630f73fa-8865-4bea-81b7-8f2bbf9c0c9b"

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
